"""
ForgeSight — ReportLab PDF reports (§5.4 reporting outputs). Two structured reports:
  - generate_alert_report(...)  : per-equipment abnormal-alert report (health + alerts + history)
  - draft_shift_summary(...)    : plant-wide shift summary (open alerts + priority order)
Both return PDF bytes (the server streams them); deterministic layout, no external calls.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle)

_STEEL = colors.HexColor("#1F4E79")
_MOLTEN = colors.HexColor("#C2410C")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("H", parent=ss["Title"], textColor=_STEEL, fontSize=18, spaceAfter=4))
    ss.add(ParagraphStyle("Sub", parent=ss["Normal"], textColor=colors.grey, fontSize=9, spaceAfter=10))
    ss.add(ParagraphStyle("Sec", parent=ss["Heading2"], textColor=_STEEL, fontSize=12, spaceBefore=8))
    return ss


def _doc(title: str):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title=title,
                            leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=16 * mm, bottomMargin=16 * mm)
    return buf, doc


def _kv_table(rows: list[tuple[str, str]]) -> Table:
    t = Table([[k, v] for k, v in rows], colWidths=[55 * mm, 110 * mm])
    t.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 9),
        ("TEXTCOLOR", (0, 0), (0, -1), _STEEL),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.whitesmoke, colors.white]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _footer(ss) -> Paragraph:
    return Paragraph(
        "Generated by ForgeSight · governed multi-agent maintenance decision-support · "
        "every claim cited, every score deterministic.", ss["Sub"])


def generate_alert_report(*, equipment: dict, health: dict | None,
                          alerts: list[dict], breakdowns: list[dict] | None = None) -> bytes:
    """Abnormal-alert report for one equipment (§5.4 · §5.1)."""
    ss = _styles()
    buf, doc = _doc(f"Abnormal Alert Report — {equipment.get('id')}")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story = [
        Paragraph("Abnormal Alert Report", ss["H"]),
        Paragraph(f"{equipment.get('name','?')} · {equipment.get('id','?')} · "
                  f"zone {equipment.get('zone','?')} · criticality {equipment.get('criticality','?')} "
                  f"· {now}", ss["Sub"]),
    ]
    h = health or {}
    story += [Paragraph("Equipment health", ss["Sec"]), _kv_table([
        ("Anomaly score", str(h.get("anomaly_score", "—"))),
        ("Status", "ANOMALOUS" if h.get("is_anomalous") else "nominal"),
        ("Estimated RUL (days)", str(h.get("rul_days", "—"))),
        ("Contributing sensors", ", ".join(h.get("contributing_sensors") or []) or "—"),
    ]), Spacer(1, 6)]

    arows = [["Severity", "Title", "Raised"]] + [
        [a.get("severity", ""), a.get("title", ""), str(a.get("created_at", ""))[:19]]
        for a in (alerts or [])[:12]] or [["Severity", "Title", "Raised"], ["—", "no open alerts", "—"]]
    at = Table(arows, colWidths=[24 * mm, 110 * mm, 31 * mm])
    at.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 8),
        ("BACKGROUND", (0, 0), (-1, 0), _STEEL), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey), ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story += [Paragraph("Open alerts", ss["Sec"]), at, Spacer(1, 6)]

    if breakdowns:
        story += [Paragraph("Related history", ss["Sec"])]
        for b in breakdowns[:5]:
            chip = " &#10003; engineer-verified" if b.get("verified") else ""
            story.append(Paragraph(
                f"<b>{b.get('id','')}</b> ({b.get('occurred_at','')}) — {b.get('fault_code','')}: "
                f"{b.get('root_cause','')}{chip}", ss["Normal"]))
    story += [Spacer(1, 10), _footer(ss)]
    doc.build(story)
    return buf.getvalue()


def draft_shift_summary(*, alerts: list[dict], equipment: list[dict] | None = None,
                        priorities: list[dict] | None = None) -> bytes:
    """Plant-wide shift summary for supervisors (§5.4 · §5.2)."""
    ss = _styles()
    buf, doc = _doc("Shift Summary")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    crit = sum(1 for a in alerts or [] if a.get("severity") in ("high", "critical"))
    story = [
        Paragraph("Shift Summary", ss["H"]),
        Paragraph(f"{now} · {len(alerts or [])} open alerts ({crit} high/critical)", ss["Sub"]),
        Paragraph("Open alerts (most recent first)", ss["Sec"]),
    ]
    arows = [["Severity", "Equipment", "Title"]] + [
        [a.get("severity", ""), a.get("equipment_id", ""), a.get("title", "")]
        for a in (alerts or [])[:15]] or [["Severity", "Equipment", "Title"], ["—", "—", "no open alerts"]]
    at = Table(arows, colWidths=[24 * mm, 40 * mm, 101 * mm])
    at.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 8),
        ("BACKGROUND", (0, 0), (-1, 0), _MOLTEN), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey), ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(at)
    if priorities:
        story += [Paragraph("Recommended order tonight", ss["Sec"])]
        for i, p in enumerate(priorities[:8], 1):
            story.append(Paragraph(
                f"{i}. <b>{p.get('equipment_id', p.get('name',''))}</b> — "
                f"score {p.get('score','?')} ({p.get('reason','')})", ss["Normal"]))
    story += [Spacer(1, 10), _footer(ss)]
    doc.build(story)
    return buf.getvalue()
